const langdata = {
  en: {
    "help-center": "Help center",
    "in-this-guide": "IN THIS GUIDE",
    "prizy-gift-cards":"Prizy gift cards",
    "guidelines":"Prizy gift cards : Guidelines",
    "t1":"About our Prizy gift cards",
    "t2":"Prizy gift cards general information",
    "t2q1": " Prizy gift card reception channels",
    "t2q2": " Where can I find the initial value of my Prizy gift card?", 
    "t2q3": " Where can I find the type of my Prizy gift card ?", 
    "t2q4": "Where can I find the expiry date of my Prizy gift card ?",
    "t2q5": " My Prizy gift card payment information",

    "t3": "How do I use a Prizy gift card?",
    "t3q1": "Where can I use my Prizy gift card ?",
    "t3q2": "How do I make a payment with my Prizy gift card ?",
    "t3q3": "Is it possible to use my Prizy gift cards online ?",
    "t3q4": "How can I use my Prizy gift card online ?",
    "t3q5": "How can I track my Prizy gift card purchases ?",
    "t3q6": "How can I check my Prizy gift card balance ?",
    "t3q7": "Is it possible to use my Prizy gift card during offers/promotions ?",

    "t4": " In case of a problem",
    "t4q1": "What happens if my Prizy gift card is refused ?",
    "t4q2": "What should I do if I notice that my gift card has been used fraudulently ?",
    "t4q3": "Can I use my gift card after the expiry date ?",
    "t4q4": "What should I do if I need to return or exchange a product in one of the partner stores ?",
    "t4q5": "Your question is not in the list",

    "p1": "Preview how to receive and use our Prizy gift cards to make purchases in our network of partner boutiques.",
    "p2": "Last updated July 31, 2023",
    "p3": "Prizy gift cards offer their beneficiaries the possibility of using them in a vast network of partners, covering various categories such as ready-to-wear, accessories, household appliances, electronics, sports, wellness and food. What's more, they can be used on partner websites listed in our catalog.",
    "p4": "You have the flexibility of using your gift card in several transactions, in different stores, as long as the balance of the gift and the expiry date have not been exceeded.",
    "p5": "Prizy's digital gift cards have been specially developed to be associated with the beneficiary's e-mail address. You will therefore receive your gift card by e-mail, sent by the company or person who wishes to give it to you. However, once you've received it by e-mail, you also have the option of printing it out if you wish.",
    "p6": "When you receive the e-mail containing your Prizy gift card, one of the elements provided is the value of the card. You can easily locate this information in the top left-hand corner of the e-mail, just below your name, as shown in the example below.",
    "p7": "figure 1: Gift card value",
    "p8": "Prizy offers a wide variety of gift cards <a  href='https://prizy.co/offers' class='link' target='_blank'>(see our offers)</a> that differ from one another according to the group of stores where they can be used.",
    "p9": "To identify the type of gift card you have received, simply look at the image in the e-mail, just after the total value of the card, as shown in the example below:",
    "p10": "figure 2: Gift card type",
    "p11": "If your e-mail software does not display images by default (e.g. Outlook), please configure it manually to display all gift card details correctly.",
    "p12": "Our gift cards have an important feature: their validity is defined over a given period, between a start date (before which the card cannot be used) and an expiry date (after which the card can no longer be used).",
    "p13": "These specific dates are clearly indicated in the e-mail containing the gift card, just after the image identifying the card type, as shown in <a class='link' href='#figure2'>the previous figure </a>.",
    "p14": "To make a payment with a Prizy gift card, you'll only need two pieces of information:",
    "p15": "The gift card key: This is available in two different formats, either as a QR code, or as a text. You'll need to present this key to the store cashier, who will scan or enter it depending on the format provided.",
    "p16": "The secret code: This 4-digit code will be requested by the shop assistant to finalize your transaction.",
    "p17": " All of this essential information can be found in the gift card's e-mail, as illustrated in the image below:",

    "p18": "figure 3: Payment information",
    "p19": "Depending on the type of gift card you have, you will be able to use it in a number of our stores or partner websites affiliated with Prizy. To consult the complete list of these partners, simply click on the 'Partner stores' button located at the bottom of your e-mail, just below the gift card key, as shown in the illustration below:",
    "p20": "figure 4: Partner stores",
    "p21": "By clicking on this button, you will be redirected to a new page presenting our affiliated partners. By selecting one of the brands in the list, you'll be taken to another page listing the stores of that brand where you can use your card, along with their opening hours and location. If the store also offers online sales, a link to their website will enable you to use your card on their platform.",
    "p22": "figure 5: Where can I use my Prizy gift card?",
    "p23": "Please note that some chains may have more stores than those shown in the list. In this case, your card can only be used in the stores specified.",
    
    "p24": "To make a payment with your Prizy gift card, please follow the instructions described in <a href='#t2q5' class='link'>the previous section</a>.",
    "p25": "To use your gift card in one of our partner stores, simply select the brand of your choice from the list. If you find a 'website' section with a link to the corresponding site, you'll be able to use your gift card online. If you don't see the link, unfortunately, it won't be possible",
    "p26": "figure 6: Example of a store where online purchasing is possible",
    "p27": "Please note that sometimes one of our partner stores offers online sales via its website, but you do not find their website in the list of stores (as is the case with Zara, for example). In this case, regrettably, your gift card cannot be used online. That's why it's always important to check the store listing for up-to-date information.",
    "p28": "To use your gift card for online payment, follow these simple steps :",

    "p29": "First of all, make sure that using the gift card is possible online <a class='link' href='#t3q3'>(see previous question)</a>",

    "p30": "Proceed with your online purchase as usual",
    "p31": "When the company contacts you to confirm your order, clearly indicate that you wish to use Prizy as a payment method",
    "p32": "You will then receive a payment request by e-mail, where you must enter your gift card payment details, including the key and secret code",
    "p33": "Once the payment request has been validated, you will receive a confirmation of your order",
    "p34": "Each time you make a purchase using your gift card, you will receive a summary e-mail containing the details of your transaction, such as the date, place of purchase, amount spent and balance remaining on your gift card.",
    "p35": "If you have not yet used your gift card, you can check the initial balance by consulting the gift card e-mail you received.",
    "p36": "On the other hand, if you have already made purchases with the card, to find out the balance remaining on the card, simply consult the last purchase confirmation e-mail you received when you made your last transaction.",
    "p37": "During sales, the use of a Prizy gift card follows the sales rules of each store. We recommend that you contact the store you are interested in directly before visiting, to make sure of the details. Their contact details can be found on their special pages in our brands page <a  class='link' href='#figure5'>(see figure)</a>.",
    "p39": "In case of confusion or problems, please do not hesitate to contact our customer service. You'll find our contact details at the bottom of the e-mail containing your gift card. Our team will be delighted to help you.",

    "p40": "You should call this number right away <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a> or send an email to this address <a class='link' target='_blank' href='mailto:contact@prizy.co'>contact@prizy.co</a>.",
    "p41": "You need to call this number right away <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a>.",

    "p43": "Returns and exchanges are governed by the terms and conditions of sale of each brand. However, in the event of an accepted return, the vendor in charge of the transaction must provide proof of your return so that we can proceed with the refund of the transaction amount.",
    "p44": "Contact our helpdesk for any further questions",
    "p45": "Reinventing Rewards in the workplace",
    "p46":"© Prizy, 2023. All rights reserved.",

    "p38": "Note",
    "title":"Prizy gift cards - Help center",


    
  },
  fr: {
    "help-center": "Centre d'aide",
    "in-this-guide": "DANS CE GUIDE",
    "prizy-gift-cards":"Cartes cadeaux Prizy",
    "guidelines":"Cartes cadeaux Prizy : Mode d’emploi",
    "t1":"À propos de nos cartes cadeaux Prizy",
    "t2":"Informations générales sur les cartes cadeaux Prizy",
    "t2q1":"Canaux de réception d’une carte cadeau Prizy",
    "t2q2":"Connaître le montant total de ma carte cadeau Prizy",
    "t2q3":"Connaître le type de ma carte cadeau Prizy",
    "t2q4":"Connaître la date de validité de ma carte cadeau Prizy",
    "t2q5":"Informations de paiement de ma carte cadeau Prizy",

    "t3":"Comment utiliser une carte cadeau Prizy ?",
    "t3q1":"Où consommer ma carte cadeau Prizy ?",
    "t3q2":"Comment effectuer un paiement avec ma carte cadeau Prizy ?",
    "t3q3":"Est-il possible d'utiliser mes cartes cadeaux Prizy en ligne ?",
    "t3q4":"Comment utiliser ma carte cadeau Prizy en ligne ?",
    "t3q5":"Comment faire le suivi de mes achats faits avec ma carte cadeau Prizy ?",
    "t3q6":"Comment consulter le solde de ma carte cadeau Prizy ?",
    "t3q7":"Est-il possible d’utiliser ma carte cadeau Prizy pendant les offres/promotions ?",

    "t4":"En cas de problème",
    "t4q1":"Que se passe-t-il si on me refuse ma carte cadeau Prizy ?",
    "t4q2":"Que dois-je faire si je m'aperçois que ma carte cadeau a été utilisée frauduleusement ?",
    "t4q3":"Est-ce que je peux utiliser ma carte cadeau après le délai de validité ?",
    "t4q4":"Que dois-je faire en cas de retour ou d'échange produit dans une des enseignes partenaires ?",
    "t4q5":"Votre question ne figure pas dans la liste ?",

    "p1":"Prévisualisez la façon de recevoir et d'utiliser nos cartes cadeaux Prizy pour faire des achats dans notre réseau de boutiques partenaires.",
    "p2":"Dernière mise à jour le 31 juillet 2023",
    "p3":"Les cartes cadeaux Prizy offrent à leurs bénéficiaires la possibilité de les utiliser dans un vaste réseau de partenaires, couvrant diverses catégories telles que le prêt-à-porter, les accessoires, l'électroménager, l'électronique, le sport, le bien-être, et l'agroalimentaire. De plus, elles peuvent être utilisées sur les sites web partenaires répertoriés dans notre catalogue.",
    "p4":"Vous avez la flexibilité d'utiliser votre carte cadeau en plusieurs fois, dans différentes enseignes, tant que son solde n'est pas épuisé et sa date de validité n'est pas dépassée.",
    "p5":"Les cartes cadeaux digitales de Prizy ont été spécialement développées pour être associées à l'adresse électronique du bénéficiaire. Vous recevrez alors votre carte cadeau par e-mail, envoyée par l'entreprise ou la personne qui souhaite vous l'offrir. Cependant, une fois que vous l'avez reçue par courrier électronique, vous avez également la possibilité de l'imprimer si vous le désirez.",
    "p6":"Lorsque vous recevez l'e-mail contenant votre carte cadeau Prizy, l'un des éléments fournis est le montant de celle-ci. Vous pourrez facilement repérer cette information dans le coin supérieur gauche de l'e-mail, juste sous votre nom, comme illustré dans l'exemple ci-dessous.",
    "p7":"figure 1 : Montant de la carte cadeau",
    "p8":"Prizy offre une variété étendue de cartes cadeaux <a href='https://prizy.co/offers' class='link' target='_blank'>(voir nos offres)</a> qui se distinguent les unes des autres en fonction du groupe d'enseignes où elles peuvent être utilisées.",
    "p9":"Pour identifier le type de carte cadeau que vous avez reçu, il vous suffit de consulter l'image présente dans l'e-mail, juste après le montant total de la carte, comme le montre l'exemple ci-dessous :",
    "p10":"figure 2 : Type de la carte cadeau",
    "p11":"Si votre logiciel de messagerie n'affiche pas les images par défaut (par exemple, Outlook), veuillez le configurer manuellement pour visualiser tous les détails de la carte cadeau correctement.",
    "p12":"Nos cartes cadeaux possèdent une caractéristique importante : leur validité est définie sur une période donnée, entre une date de début de validité (avant laquelle la carte ne peut être utilisée) et une date d'expiration (après laquelle la carte n'est plus utilisable).",
    "p13":"Ces dates spécifiques sont clairement indiquées dans l'e-mail contenant la carte cadeau, juste après l'image qui identifie le type de carte, comme illustré dans la <a class='link' href='#figure2'> figure précédente</a>.",
    "p14":"Pour effectuer un paiement avec une carte cadeau Prizy, vous aurez uniquement besoin de deux informations :",
    "p15":"La clé de la carte cadeau : Celle-ci est disponible sous deux formats différents, soit sous forme de QR code, soit sous format texte. Vous devrez présenter cette clé au caissier du magasin, qui la scannera ou la saisira en fonction du format fourni.",
    "p16":"Le code secret : Ce code à 4 chiffres vous sera demandé par le vendeur pour finaliser votre transaction.",
    "p17":"Toutes ces informations essentielles sont disponibles dans l'e-mail de la carte cadeau, comme l'illustre l'image ci-dessous:",

    "p18":"figure 3 : Informations de paiement",
    "p19":"En fonction du type de carte cadeau que vous avez, vous pourrez l'utiliser dans un certain nombre de magasins ou de sites web partenaires affiliés à Prizy. Pour consulter la liste complète de ces partenaires, il vous suffit de cliquer sur le bouton 'Enseignes partenaires' situé en bas de votre e-mail, juste en dessous de la clé de la carte cadeau, comme le montre l'illustration ci-dessous :",
    "p20":"figure 4 : Enseignes partenaires",
    "p21":"En cliquant sur ce bouton, vous serez redirigé vers une nouvelle page qui présente les partenaires affiliés. En choisissant l'une des enseignes de la liste, vous accéderez à une autre page qui répertorie les magasins de cette enseigne où vous pourrez utiliser votre carte, ainsi que leurs horaires d'ouverture et leur emplacement. Si le magasin propose également des ventes en ligne, un lien vers leur site web vous permettra d'utiliser votre carte sur leur plateforme.",
    "p22":"figure 5 : Où consommer ma carte cadeau Prizy ?",
    "p23":"Veuillez noter que certaines enseignes peuvent avoir plus de magasins que ceux indiqués dans la liste. Dans ce cas, votre carte ne pourra être utilisée que dans les magasins spécifiés.",
    
    "p24":"Pour effectuer un paiement avec votre carte cadeau Prizy, veuillez suivre les instructions décrites dans la <a href='#t2q5' class='link'>section précédente</a>.",
    "p25":"Pour utiliser votre carte cadeau dans l'une de nos enseignes partenaires, sélectionnez simplement l'enseigne de votre choix dans la liste. Si vous repérez une rubrique 'site web' avec un lien vers le site correspondant, alors vous pourrez effectivement utiliser votre carte cadeau en ligne. En revanche, si cette rubrique n'est pas présente, malheureusement, l'utilisation en ligne ne sera pas possible.",
    "p26":"figure 6 : Exemple d'une enseigne où l'achat en ligne est possible",
    
    "p27":"Veuillez noter qu'il peut arriver qu'une de nos enseignes partenaires propose des ventes en ligne via son site web, mais que vous ne le trouviez dans la liste des magasins (comme c'est le cas par exemple avec Zara). Dans cette situation, regrettablement, votre carte cadeau ne pourra pas être utilisée en ligne. C'est pourquoi il est toujours essentiel de vérifier la liste des magasins pour obtenir des informations à jour.",
    "p28":"Pour utiliser votre carte cadeau pour un paiement en ligne, suivez ces étapes simples :",
    
    "p29":"Assurez-vous tout d’abord que l’utilisation de la carte cadeau est possible en ligne <a class='link' href='#t3q3'>(voir question précédente)</a>",
    
    "p30":"Procéder à votre achat en ligne comme d’habitude",
    "p31":"Lorsque l’enseigne vous contacte pour confirmer votre commande, indiquez clairement que vous souhaitez utiliser Prizy comme moyen de paiement",
    "p32":"Suite à cela vous recevrez une demande de paiement par e-mail, où vous devrez saisir les informations de paiement de votre carte cadeau, notamment la clé et le code secret",
    "p33":"Une fois la demande de paiement validée, vous obtiendrez la confirmation de votre commande",
    "p34":"À chaque fois que vous effectuez un achat en utilisant votre carte cadeau, vous recevez un e-mail récapitulatif contenant les détails de votre transaction, tels que la date, le lieu de l'achat, le montant dépensé et le solde restant sur votre carte cadeau.",
    "p35":"Si vous n'avez pas encore utilisé votre carte cadeau, vous pouvez vérifier le solde initial de celle-ci en consultant l'e-mail contenant la carte cadeau que vous avez reçu.",
    "p36":"En revanche, si vous avez déjà effectué des achats avec la carte, pour connaître le solde restant sur celle-ci, il vous suffit de consulter le dernier e-mail de confirmation d'achat que vous avez reçu lors de votre dernière transaction.",
    "p37":"Pendant les soldes, l'utilisation d'une carte cadeau Prizy suit les règles de vente de chaque magasin. Il est recommandé de contacter directement le magasin qui vous intéresse avant de vous déplacer, pour vous assurer des détails. Leurs coordonnées se trouvent sur leurs pages spéciales, dans notre espace enseignes <a  class='link' href='#figure5'>(voir figure)</a>.",
    "p39":"En cas de confusion ou de problème, n'hésitez pas à contacter notre service clientèle. Vous trouverez nos coordonnées en bas de l'e-mail contenant votre carte cadeau. Notre équipe se fera un plaisir de vous aider.",
    "p40":"Vous devez appeler tout de suite ce numéro <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a> ou envoyer un mail à cette adresse <a class='link' target='_blank' href='mailto:contact@prizy.co'>contact@prizy.co</a>.",
    
    "p41":"Vous devez appeler ce numéro tout de suite <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a>.",
    "p42":"Malheureusement, il n'est pas possible d'utiliser votre carte cadeau au-delà de sa date de validité.",
    
    "p43":"Les retours et les échanges sont régis selon les conditions de ventes de chacune des enseignes. Cependant, en cas de retour accepté, le vendeur en charge de la transaction doit transmettre le justificatif de votre retour afin que l'on procède au remboursement du montant de la transaction.",
    "p44":"Contactez notre service d'assistance pour toute autre question",
    "p45":"Reinventer Recompense en entreprise",
    "p46":"© Prizy, 2023. Tous droits réservés.",

    "p38":"Remarque",
    "title":"Cartes cadeaux Prizy - Centre d'aide",

  },
  ar: {
    "help-center": "مركز المساعدة",
    "in-this-guide": "في هذا الدليل",
    "prizy-gift-cards":"بطاقات هدايا Prizy ",
    "guidelines":"بطاقات الهدايا Prizy : تعليمات الاستخدام",
    "t1":"حول بطاقات الهدايا الخاصة بنا",
    "t2":"معلومات عامة عن بطاقات هدايا Prizy ",
    "t2q1":"قنوات تلقي بطاقة هدايا Prizy ",
    "t2q2":"معرفة المبلغ الإجمالي لبطاقة هدايا Prizy ",
    "t2q3":"معرفة نوع بطاقة هدايا Prizy ",
    "t2q4":"معرفة تاريخ صلاحية بطاقة هدايا Prizy ",
    "t2q5":"معلومات الدفع لبطاقة هدايا Prizy ",

    "t3":"كيف تستخدم بطاقة هدايا Prizy ؟",
    "t3q1":"أين يمكنني استهلاك بطاقة هدايا Prizy  الخاصة بي؟",
    "t3q2":"كيف يمكنني الدفع باستخدام بطاقة هدايا Prizy  الخاصة بي؟",
    "t3q3":"هل من الممكن استخدام بطاقات هدايا Prizy  الخاصة بي عبر الإنترنت؟",
    "t3q4":"كيف يمكنني استخدام بطاقة هدايا Prizy  الخاصة بي عبر الإنترنت؟",
    "t3q5":"كيف يمكنني تتبع مشترياتي التي أجريت باستخدام بطاقة هدايا Prizy  الخاصة بي؟",
    "t3q6":"كيف يمكنني التحقق من رصيد بطاقة هدايا Prizy  الخاصة بي؟",
    "t3q7":"هل من الممكن استخدام بطاقة هدايا Prizy  أثناء العروض/الترقيات؟",

    "t4":"في حالة وجود مشكلة",
    "t4q1":"ماذا يحدث إذا تم رفض بطاقة هدايا Prizy  الخاصة بي؟",
    "t4q2":"ماذا علي أن أفعل إذا وجدت أن بطاقة الهدايا الخاصة بي قد استخدمت عن طريق الاحتيال؟",
    "t4q3":"هل يمكنني استخدام بطاقة الهدايا الخاصة بي بعد فترة الصلاحية؟",
    "t4q4":"ماذا يجب أن أفعل في حالة إرجاع المنتج أو استبداله في إحدى العلامات التجارية الشريكة؟",
    "t4q5":"سؤالك ليس في القائمة؟",

    "p1":"معاينة كيفية استلام واستخدام بطاقات هدايا Prizy  الخاصة بنا لإجراء عمليات شراء في شبكتنا من المتاجر الشريكة.",
    "p2":"آخر تحديث في 31 يوليو 2023",
    "p3":"توفر بطاقات الهدايا Prizy للمستفيدين منها الفرصة لاستخدامها في شبكة واسعة من الشركاء، تغطي فئات مختلفة مثل الملابس الجاهزة والإكسسوارات والأجهزة المنزلية والإلكترونيات والرياضة والرفاه والأغذية الزراعية. بالإضافة إلى ذلك، يمكن استخدامها على مواقع الويب الشريكة المدرجة في الكتالوج الخاص بنا.",
    "p4":"لديك المرونة لاستخدام بطاقة الهدايا الخاصة بك على عدة أقساط، في علامات تجارية مختلفة، طالما لم يتم تجاوز مبلغ الوقف وتاريخ الصلاحية.",
    "p5":"تم تطوير بطاقات الهدايا الرقمية الخاصة ب Prizy خصيصا لربطها بعنوان البريد الإلكتروني للمستفيد. ستتلقى بعد ذلك بطاقة الهدايا الخاصة بك عن طريق البريد الإلكتروني، التي ترسلها الشركة أو الشخص الذي يرغب في تقديمها لك. ومع ذلك، بمجرد استلامه عن طريق البريد الإلكتروني، لديك أيضا خيار طباعته إذا كنت ترغب في ذلك.",
    "p6":"عندما تتلقى البريد الإلكتروني الذي يحتوي على بطاقة هدايا Prizy  الخاصة بك، فإن أحد العناصر المقدمة هو مقدارها. يمكنك بسهولة تحديد موقع هذه المعلومات في الزاوية اليسرى العليا من البريد الإلكتروني، أسفل اسمك مباشرة، كما هو موضح في المثال أدناه.",
    "p7":"الشكل 1: مبلغ بطاقة الهدايا",
    "p8":"تقدم Prizy  مجموعة واسعة من بطاقات الهدايا <a href='https://prizy.co/offers' class='link' target='_blank'>(انظر عروضنا)</a> التي تختلف عن بعضها البعض اعتمادا على مجموعة العلامات التجارية التي يمكن استخدامها فيها.",
    "p9":"لتحديد نوع بطاقة الهدايا التي تلقيتها، ما عليك سوى الرجوع إلى الصورة في البريد الإلكتروني، مباشرة بعد المبلغ الإجمالي للبطاقة، كما هو موضح في المثال أدناه:",
    "p10":"الشكل 2: نوع بطاقة الهدايا",
    "p11":"إذا كان برنامج بريدك الإلكتروني لا يعرض الصور الافتراضية (على سبيل المثال، Outlook)، فيرجى تكوينه يدويا لعرض جميع تفاصيل بطاقة الهدايا بشكل صحيح.",
    "p12":"تتميز بطاقات الهدايا الخاصة بنا بميزة مهمة: يتم تعريف صلاحيتها على مدى فترة معينة، بين تاريخ بدء الصلاحية (الذي لا يمكن استخدام البطاقة قبله) وتاريخ انتهاء الصلاحية (بعد ذلك لم تعد البطاقة قابلة للاستخدام).",
    "p13":"يشار بوضوح إلى هذه التواريخ المحددة في البريد الإلكتروني الذي يحتوي على بطاقة الهدايا، مباشرة بعد الصورة التي تحدد نوع البطاقة، كما هو موضح في<a class='link' href='#figure2'>الشكل السابق.</a>.",
    "p14":"لإجراء الدفع باستخدام بطاقة هدايا Prizy ، ستحتاج فقط إلى قطعتين من المعلومات:",
    "p15":"مفتاح بطاقة الهدايا: إنه متاح بتنسيقين مختلفين، إما على شكل رمز الاستجابة السريعة أو على شكل تنسيق نصي. سيتعين عليك تقديم هذا المفتاح إلى أمين صندوق المتجر، الذي سيقوم بمسحه ضوئيا أو إدخاله وفقا للتنسيق المقدم.",
    "p16":"الرمز السري: سيطلب البائع هذا الرمز المكون من 4 أرقام لإنهاء معاملتك.",
    "p17":"كل هذه المعلومات الأساسية متاحة في البريد الإلكتروني لبطاقة الهدايا، كما هو موضح في الصورة أدناه:",

    "p18":"الشكل 3: معلومات الدفع",
    "p19":"اعتمادا على نوع بطاقة الهدايا التي لديك، يمكنك استخدامها في عدد من المتاجر أو المواقع الإلكترونية الشريكة التابعة لشركة Prizy. للاطلاع على القائمة الكاملة لهؤلاء الشركاء، ما عليك سوى النقر على زر 'علامات الشريك' الموجود في أسفل بريدك الإلكتروني، أسفل مفتاح بطاقة الهدايا مباشرة، كما هو موضح في الرسم التوضيحي أدناه:",
    "p20":"الشكل 4: علامات الشريك",
    "p21":"بالنقر فوق هذا الزر، ستتم إعادة توجيهك إلى صفحة جديدة تعرض الشركاء التابعين. باختيار إحدى العلامات التجارية في القائمة، ستدخل إلى صفحة أخرى تسرد المتاجر في هذه العلامة التجارية حيث يمكنك استخدام خريطتك، بالإضافة إلى ساعات عملها وموقعها. إذا كان المتجر يقدم أيضا مبيعات عبر الإنترنت، فسيسمح لك رابط لموقعه على الويب باستخدام بطاقتك على منصتهم.",
    "p22":"الشكل 5: أين أستهلك بطاقة هدايا Prizy  الخاصة بي؟",
    "p23":"يرجى ملاحظة أن بعض العلامات التجارية قد يكون لديها متاجر أكثر من تلك المشار إليها في القائمة. في هذه الحالة، لا يمكن استخدام بطاقتك إلا في المتاجر المحددة.",
    
    "p24":"لإجراء الدفع باستخدام بطاقة هدايا Prizy  الخاصة بك، يرجى اتباع التعليمات الموضحة في <a href='#t2q5' class='link'>القسم السابق</a>.",
    "p25":"لاستخدام بطاقة الهدايا الخاصة بك في إحدى العلامات التجارية الشريكة لنا، ما عليك سوى تحديد العلامة التجارية التي تختارها من القائمة. إذا وجدت قسم 'موقع ويب' به رابط إلى الموقع المقابل، فيمكنك بالفعل استخدام بطاقة الهدايا الخاصة بك عبر الإنترنت. من ناحية أخرى، إذا لم يكن هذا القسم موجودا، لسوء الحظ، فلن يكون الاستخدام عبر الإنترنت ممكنا.",
    "p26":"الشكل 6: مثال على علامة حيث يمكن الشراء عبر الإنترنت",
    
    "p27":"يرجى ملاحظة أنه قد يحدث أن تقدم إحدى العلامات التجارية الشريكة لنا خدمة البيع عبر الإنترنت عبر موقعها الإلكتروني، ولكنك لا تجده في قائمة المتاجر (كما هو الحال على سبيل المثال مع زارا). في هذه الحالة، للأسف، لا يمكن استخدام بطاقة الهدايا الخاصة بك عبر موقعهم. لذا فأنه من الضروري دائما التحقق من قائمة المتاجر للحصول على أحدث المعلومات.",
    "p28":"لاستخدام بطاقة الهدايا الخاصة بك للدفع عبر الإنترنت، اتبع هذه الخطوات البسيطة:",
    
    "p29":"تأكد من أن استخدام بطاقة الهدايا ممكن عبر الإنترنت <a class='link' href='#t3q3'>(انظر السؤال السابق)</a>",
    
    "p30":"تابع عملية الشراء عبر الإنترنت كالمعتاد",
    "p31":"عندما تتصل بك العلامة التجارية لتأكيد طلبك، اذكر بوضوح أنك تريد استخدام Prizy  كوسيلة للدفع",
    "p32":"بعد ذلك، ستتلقى طلب دفع عن طريق البريد الإلكتروني، حيث سيتعين عليك إدخال معلومات الدفع الخاصة ببطاقة الهدايا الخاصة بك، بما في ذلك المفتاح والرمز السري",
    "p33":"بمجرد التحقق من صحة طلب الدفع، ستحصل على تأكيد لطلبك",
    "p34":"في كل مرة تقوم فيها بعملية شراء باستخدام بطاقة الهدايا الخاصة بك، تتلقى بريدا إلكترونيا موجزا يحتوي على تفاصيل معاملتك، مثل تاريخ ومكان الشراء والمبلغ الذي تم إنفاقه والرصيد المتبقي على بطاقة الهدايا الخاصة بك.",
    "p35":"إذا لم تكن قد استخدمت بطاقة الهدايا الخاصة بك بعد، فيمكنك التحقق من الرصيد الأولي لبطاقة الهدايا الخاصة بك عن طريق الرجوع إلى البريد الإلكتروني الذي يحتوي على بطاقة الهدايا التي تلقيتها.",
    "p36":"من ناحية أخرى، إذا كنت قد قمت بالفعل بعمليات شراء باستخدام البطاقة، لمعرفة الرصيد المتبقي عليها، فما عليك سوى الرجوع إلى آخر بريد إلكتروني لتأكيد الشراء تلقيته خلال معاملتك الأخيرة.",
    "p37": "أثناء العروض/الترقيات، يتبع استخدام بطاقة هدايا Prizy  قواعد المبيعات لكل متجر. يوصى بالاتصال بالمتجر الذي تهتم به مباشرة قبل الانتقال، لضمان التفاصيل. يمكن العثور على تفاصيل الاتصال الخاصة بهم على صفحاتهم الخاصة في منطقة اللافتة الخاصة بنا. <a  class='link' href='#figure5'>(انظر الشكل)</a>.",
    "p39":"في حالة حدوث مشكلة، لا تتردد في الاتصال بخدمة العملاء لدينا. ستجد تفاصيل الاتصال الخاصة بنا في أسفل البريد الإلكتروني الذي يحتوي على بطاقة الهدايا الخاصة بك. سيسعد فريقنا بمساعدتك.",
    "p40":"يجب عليك الاتصال على الفور بهذا الرقم <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a> أو إرسال بريد إلكتروني إلى هذا العنوان <a class='link' target='_blank' href='mailto:contact@prizy.co'>contact@prizy.co</a>.",
    
    "p41":"يجب عليك الاتصال بهذا الرقم على الفور <a dir='ltr' class='link' target='_blank' href='tel:0550576644'>(+213) 550 57 66 44</a>.",
    "p42":"لسوء الحظ، لا يمكن استخدام بطاقة الهدايا الخاصة بك بعد تاريخ صلاحيتها.",
    
    "p43":"تخضع المرتجعات والتبادلات وفقا لشروط المبيعات لكل علامة تجارية. ومع ذلك، في حالة الإرجاع المقبول، يجب على البائع المسؤول عن المعاملة إرسال دليل على عودتك حتى يمكن رد مبلغ المعاملة.",
    "p44":"اتصل بخدمة الدعم الخاصة بنا لأي أسئلة أخرى",
    "p45":"إعادة اختراع المكافأة في العمل",
    "p46":"© Prizy، 2023. جميع الحقوق محفوظة.",

    "p38":"ملاحظة",
    "title":"بطاقات هدايا Prizy - مركز المساعدة",

  },
};
